# Generated by Django 3.0.8 on 2020-07-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name': 'Habitacion', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelTable(
            name='habitacion',
            table=None,
        ),
    ]
