# Generated by Django 3.0.8 on 2020-07-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_auto_20200711_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='Descripcion',
            new_name='descripcion',
        ),
    ]
