# Generated by Django 3.0.8 on 2020-07-11 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0003_auto_20200711_2007'),
        ('arduino_habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduino_habitaciones',
            name='id_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion'),
        ),
    ]
