# Generated by Django 3.0.8 on 2020-07-11 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0003_auto_20200711_2007'),
        ('arduino_habitaciones', '0003_auto_20200711_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensores_arduino_habitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sensor', models.CharField(max_length=3, verbose_name='Estado Sensor')),
                ('valor_sensor', models.CharField(max_length=3, verbose_name='Valor Sensor')),
                ('id_arduino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino_habitaciones.arduino_habitaciones')),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
            ],
            options={
                'verbose_name': 'sensores_arduino_habitacion',
                'verbose_name_plural': 'sensores_arduino_habitaciones',
            },
        ),
    ]
