# Generated by Django 3.0.7 on 2020-07-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arduino_habitaciones', '0001_initial'),
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensores_arduino_habitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=5000, verbose_name='Descripcion')),
                ('estado_sensor', models.CharField(max_length=3, verbose_name='Estado Sensor')),
                ('valor_sensor', models.CharField(max_length=3, verbose_name='Valor Sensor')),
                ('arduino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino_habitaciones.arduino_habitaciones')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
            ],
            options={
                'verbose_name': 'sensores_arduino_habitacion',
                'verbose_name_plural': 'sensores_arduino_habitaciones',
            },
        ),
    ]
