# Generated by Django 3.0.8 on 2020-07-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_habitaciones', '0004_auto_20200713_0953'),
        ('habitacion', '0003_auto_20200711_2007'),
        ('sensores_arduino_habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores_arduino_habitaciones',
            name='id_arduino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino_habitaciones.arduino_habitaciones'),
        ),
        migrations.AlterField(
            model_name='sensores_arduino_habitaciones',
            name='id_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion'),
        ),
    ]
